### ISSUE TITLE
Tabs are center-aligned by default

### ISSUE THREAD

**Issue by kleuter** [RolfHausen/qtcreator-TabbedEditor-plugin#1]
I don't think it looks great:

<img width="2086" alt="Screenshot 2021-08-18 at 17 01 53" src="https://user-images.githubusercontent.com/2600624/129922529-d724b0c4-1910-46bb-8284-c8679ce6fd28.png">

When using document mode (QTabBar::setDocumentMode(true)) it's better
<img width="2086" alt="Screenshot 2021-08-18 at 17 05 37" src="https://user-images.githubusercontent.com/2600624/129922894-5188cd33-d8c2-4378-aa06-74ef8adf69f7.png">

macOS 10.15 / Qt Creator 4.15.2 / Qt 5.15.4

**Comment by RolfHausen** [comment]
This is just a matter of taste no fix will be made
